In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [5]:
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn import datasets

In [7]:
df = datasets.load_iris(as_frame=True).frame

In [8]:
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [9]:
df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
dtype: int64

In [10]:
df.shape

(150, 5)

In [11]:
df.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
count,150.000000,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333,1.000000
std,0.828066,0.435866,1.765298,0.762238,0.819232
min,4.300000,2.000000,1.000000,0.100000,0.000000
25%,5.100000,2.800000,1.600000,0.300000,0.000000
50%,5.800000,3.000000,4.350000,1.300000,1.000000
75%,6.400000,3.300000,5.100000,1.800000,2.000000
max,7.900000,4.400000,6.900000,2.500000,2.000000

In [13]:
X = df.drop("target", axis=1)
y = df["target"]

In [14]:
X.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [15]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y
)

In [16]:
X_train.head()

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
98                 5.1               2.5                3.0               1.1
68                 6.2               2.2                4.5               1.5
19                 5.1               3.8                1.5               0.3
143                6.8               3.2                5.9               2.3
99                 5.7               2.8                4.1               1.3

In [18]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [19]:
# Model 
svc = SVC()
svc.fit(X_train_scaled, y_train)

SVC()

In [20]:
y_pred = svc.predict(X_test_scaled)

In [23]:
# Evalute 
from sklearn.metrics import accuracy_score, classification_report, f1_score

print("accuracy: ", accuracy_score(y_test, y_pred))
print("Classification report: \n ", classification_report(y_test, y_pred))

accuracy:  0.9333333333333333
Classification report:
                precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.88      0.93      0.90        15
           2       0.93      0.87      0.90        15

    accuracy                           0.93        45
   macro avg       0.93      0.93      0.93        45
weighted avg       0.93      0.93      0.93        45

In [25]:
# lINEAR Kernel

svc = SVC(kernel="linear")
svc.fit(X_train_scaled, y_train)

y_pred = svc.predict(X_test_scaled)
print("accuracy: ", accuracy_score(y_test, y_pred))

accuracy:  0.9111111111111111

In [26]:
# ploynomial Kernel

svc = SVC(kernel="poly")
svc.fit(X_train_scaled, y_train)

y_pred = svc.predict(X_test_scaled)
print("accuracy: ", accuracy_score(y_test, y_pred))

accuracy:  0.8666666666666667

In [27]:
# sigmoid Kernel

svc = SVC(kernel="sigmoid")
svc.fit(X_train_scaled, y_train)

y_pred = svc.predict(X_test_scaled)
print("accuracy: ", accuracy_score(y_test, y_pred))

accuracy:  0.9111111111111111

In [28]:
C_vals = [0.5, 1, 2, 3, 4, 5]

for c_val in C_vals:
    svc = SVC(C=c_val, kernel="rbf")
    svc.fit(X_train_scaled, y_train)

    y_pred = svc.predict(X_test_scaled)

    print("C = ", c_val, "& accuracy: ", accuracy_score(y_test, y_pred))

C =  0.5 & accuracy:  0.9111111111111111
C =  1 & accuracy:  0.9333333333333333
C =  2 & accuracy:  0.9111111111111111
C =  3 & accuracy:  0.9111111111111111
C =  4 & accuracy:  0.9333333333333333
C =  5 & accuracy:  0.9333333333333333