In [1]:
from sklearn.svm import SVR
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score
from sklearn import datasets

In [2]:
df = datasets.load_diabetes(as_frame=True).frame

In [3]:
df.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0

In [4]:
df.shape

(442, 11)

In [5]:
df.isnull().sum()

age       0
sex       0
bmi       0
bp        0
s1        0
s2        0
s3        0
s4        0
s5        0
s6        0
target    0
dtype: int64

In [6]:
df.describe()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
count,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,442.000000
mean,-2.511817e-19,1.230790e-17,-2.245564e-16,-4.797570e-17,-1.381499e-17,3.918434e-17,-5.777179e-18,-9.042540e-18,9.293722e-17,1.130318e-17,152.133484
std,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,77.093005
min,-1.072256e-01,-4.464164e-02,-9.027530e-02,-1.123988e-01,-1.267807e-01,-1.156131e-01,-1.023071e-01,-7.639450e-02,-1.260971e-01,-1.377672e-01,25.000000
25%,-3.729927e-02,-4.464164e-02,-3.422907e-02,-3.665608e-02,-3.424784e-02,-3.035840e-02,-3.511716e-02,-3.949338e-02,-3.324559e-02,-3.317903e-02,87.000000
50%,5.383060e-03,-4.464164e-02,-7.283766e-03,-5.670422e-03,-4.320866e-03,-3.819065e-03,-6.584468e-03,-2.592262e-03,-1.947171e-03,-1.077698e-03,140.500000
75%,3.807591e-02,5.068012e-02,3.124802e-02,3.564379e-02,2.835801e-02,2.984439e-02,2.931150e-02,3.430886e-02,3.243232e-02,2.791705e-02,211.500000
max,1.107267e-01,5.068012e-02,1.705552e-01,1.320436e-01,1.539137e-01,1.987880e-01,1.811791e-01,1.852344e-01,1.335973e-01,1.356118e-01,346.000000

In [7]:
X = df.drop("target", axis=1)
y = df["target"]

In [8]:
X.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641

In [9]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [10]:
y_scaler = StandardScaler() 

y_train_scaled = y_scaler.fit_transform(
    y_train.values.reshape(-1, 1)
).ravel()   

y_test_scaled = y_scaler.transform(
    y_test.values.reshape(-1, 1)
).ravel()

In [11]:
model = SVR()

model.fit(X_train, y_train_scaled)

SVR()

In [15]:
y_pred_scaled = model.predict(X_test)

In [13]:
print ("r2: ", r2_score(y_test_scaled, y_pred_scaled))

r2:  0.48844443151651906

In [16]:
# Linear 
model = SVR(kernel="linear")
model.fit(X_train, y_train_scaled)

y_pred_train_scaled = model.predict(X_train)  
y_pred_test_scaled = model.predict(X_test)     

print("train r2:", r2_score(y_train_scaled, y_pred_train_scaled))
print("test r2:", r2_score(y_test_scaled, y_pred_test_scaled))

train r2: 0.45191229982475245
test r2: 0.4433761323833776

In [17]:
# poly 
model = SVR(kernel="poly")
model.fit(X_train, y_train_scaled)

y_pred_train_scaled = model.predict(X_train)
y_pred_test_scaled = model.predict(X_test)

print("train r2:", r2_score(y_train_scaled, y_pred_train_scaled))
print("test r2:", r2_score(y_test_scaled, y_pred_test_scaled))

train r2: 0.5790920834310542
test r2: 0.24203771038107735

In [18]:
# sigmoid
model = SVR(kernel="sigmoid")
model.fit(X_train, y_train_scaled)
y_pred_scaled = model.predict(X_test)
print("train r2:", r2_score(y_train_scaled, y_pred_train_scaled))
print ("test r2: ", r2_score(y_test_scaled, y_pred_scaled))

train r2: 0.5790920834310542
test r2:  -15.316808189576822

# Hyperprameter tuning using GridSearchCV

In [19]:
from sklearn.model_selection import GridSearchCV

In [20]:
param_grid = {
    "C": [1, 2, 5, 50, 100],
    "kernel": ["rbf", "linear"],
    "epsilon": [0.01, 0.1, 0.2, 0.3, 0.5]
}

In [21]:
svr = SVR()

grid_search = GridSearchCV(svr, param_grid, scoring="r2", cv=5)
grid_search.fit(X_train, y_train_scaled)

GridSearchCV(cv=5, estimator=SVR(),
             param_grid={'C': [1, 2, 5, 50, 100],
                         'epsilon': [0.01, 0.1, 0.2, 0.3, 0.5],
                         'kernel': ['rbf', 'linear']},
             scoring='r2')

In [22]:
print("Best parms - ", grid_search.best_params_)

Best parms -  {'C': 50, 'epsilon': 0.3, 'kernel': 'linear'}

In [23]:
# poly 
model = SVR(kernel="poly")
model.fit(X_train, y_train_scaled)

y_pred_train_scaled = model.predict(X_train)
y_pred_test_scaled = model.predict(X_test)

print("train r2:", r2_score(y_train_scaled, y_pred_train_scaled))
print("test r2:", r2_score(y_test_scaled, y_pred_test_scaled))

train r2: 0.5790920834310542
test r2: 0.24203771038107735

In [25]:
from sklearn.svm import LinearSVR

model = LinearSVR(C=10, epsilon=0.1, max_iter=5000)

model.fit(X_train, y_train_scaled)

y_train_pred_scaled = model.predict(X_train)
y_test_pred_scaled = model.predict(X_test)

print("train r2:", r2_score(y_train_scaled, y_train_pred_scaled))
print("test r2:", r2_score(y_test_scaled, y_test_pred_scaled))

train r2: 0.515281752244065
test r2: 0.4742862660457531